### PR TITLE
Response to Issues opened by @Bobnix

### PR DESCRIPTION
**Pull request by Bobnix**
Switched the sorted methods to a comparator. The tree map enforced unique method names so overloaded methods were getting overwritten

### CODE REVIEW

**Comment by njjc** [comment]
Hi Bob, this is great, thanks for all the contributions! @davidhabib, our resident ApexDoc expert, is out until Wednesday, so it will probably be until then that he reviews your pull requests.

**Comment by Bobnix** [comment]
Thanks @njjc for keeping me in the loop. I have a strong Java background so this looks like a fun project to write some code for.

**Comment by Bobnix** [comment]
Well carp, I fully expected this to be two different pull requests

**Comment by njjc** [comment]
This should be fine, if we want one change and not the other we'll let you know. I believe you should make a separate branch on your fork if you want separate pull requests.

**Comment by Bobnix** [comment]
Good idea, next fix will get its own branch for sure

**Comment by davidhabib** [comment]
looks great.  thanks Bob!

**Comment by davidhabib** [comment]
I just ran these changes locally, and I'm getting the following warnings about the comparator changes you did:

Description	Resource	Path	Location	Type
Type safety: Unchecked invocation sort(List<MethodModel>, new Comparator(){}) of the generic method sort(List<T>, Comparator<? super T>) of type Collections	ClassModel.java	/ApexDoc/src/org/salesforce/apexdoc	line 47	Java Problem
Type safety: The expression of type new Comparator(){} needs unchecked conversion to conform to Comparator<? super MethodModel>	ClassModel.java	/ApexDoc/src/org/salesforce/apexdoc	line 47	Java Problem
Comparator is a raw type. References to generic type Comparator<T> should be parameterized	ClassModel.java	/ApexDoc/src/org/salesforce/apexdoc	line 47	Java Problem
Type safety: Unchecked cast from Object to List<MethodModel>	ClassModel.java	/ApexDoc/src/org/salesforce/apexdoc	line 46	Java Problem

can you address these?

**Comment by Bobnix** [comment]
Ah, that ended up getting fixed in #34. I can take those changes and add them into this set as well if you wish.

**Comment by davidhabib** [comment]
No need.  I'm making my way through your pull requests now, so I'll get to
it.  I've been out of town for 5 days, so I'm still a bit buried and might
not get through everything this week.
thanks,
Dave


David Habib | Senior Force.com Developer | salesforcefoundation.org

**Comment by Bobnix** [comment]
Take all the time you need. That is a rather benign warning as warnings come, more of a 'I hope you know what you are doing'

**Pull request merged**
